/* 
----------------------------------------------------------
1. What is the total sales revenue?
----------------------------------------------------------
Question: What is the total sales revenue across all orders?

- Calculate the sum of the 'Total Price Usd' column for all transactions.
- Provides a high-level overview of the store's financial performance.

Why? This is the most fundamental measure of a business's performance, giving a clear picture of the total income generated from sales.
*/

SELECT SUM("Total Price Usd") AS Total_Revenue
FROM shopify_sales;

/*
The total sales revenue is the sum of the 'Total Price Usd' for all orders in the dataset.

JSON:
[
  {
    "Total_Revenue": 2746854.33
  }
]
*/

----------------------------------------------------------

/*
2. Who are the top 5 customers by total spending?
----------------------------------------------------------
Question: Identify the top 5 customers who have spent the most money.

- Group the data by 'Customer Id'.
- Calculate the sum of 'Total Price Usd' for each customer.
- Order by total spending and select the top 5.

Why? Knowing your top customers allows loyalty programs, special offers, and personalized marketing to encourage repeat business.
*/

SELECT "Customer Id", SUM("Total Price Usd") AS Total_Spent
FROM shopify_sales
GROUP BY "Customer Id"
ORDER BY Total_Spent DESC
LIMIT 5;

/*
This list shows the top 5 customers based on their total spending.


[
  { "Customer Id": "5738", "Total_Spent": 9253.53 },
  { "Customer Id": "2979", "Total_Spent": 8943.51 },
  { "Customer Id": "5537", "Total_Spent": 8780.01 },
  { "Customer Id": "4429", "Total_Spent": 8515.22 },
  { "Customer Id": "3998", "Total_Spent": 8392.42 }
]
*/
----------------------------------------------------------

/*
3. What are the sales by product category?
----------------------------------------------------------
Question: What is the breakdown of total sales revenue by product type?

- Group the data by 'Product Type'.
- Calculate the sum of 'Total Price Usd' for each product type.
- Order the results by total revenue.

Why? Helps identify best-selling product categories and those needing more marketing.
*/

SELECT "Product Type", SUM("Total Price Usd") AS Total_Revenue
FROM shopify_sales
GROUP BY "Product Type"
ORDER BY Total_Revenue DESC;

/*
This shows the total revenue generated by each product type.


[
  { "Product Type": "Tennis Shoes", "Total_Revenue": 574868.52 },
  { "Product Type": "Running Shoes", "Total_Revenue": 569837.28 },
  { "Product Type": "Climbing Shoes", "Total_Revenue": 546821.57 },
  { "Product Type": "Soccer Shoes", "Total_Revenue": 536423.44 },
  { "Product Type": "Casual Shoes", "Total_Revenue": 518903.52 }
]
*/

----------------------------------------------------------

/*
4. What is the sales performance by city?
----------------------------------------------------------
Question: Which cities are generating the most sales revenue?

- Group the data by 'CITY'.
- Calculate the sum of 'Total Price Usd' for each city.
- Order by revenue and pick the top 3 cities.

Why? Identifying top-performing cities helps guide targeted marketing and logistics.
*/

SELECT "CITY", SUM("Total Price Usd") AS Revenue
FROM shopify_sales
GROUP BY "CITY"
ORDER BY Revenue DESC
LIMIT 3;

/*
This table ranks cities by sales revenue.


[
  { "CITY": "HOUSTON", "Revenue": 177153.28 },
  { "CITY": "NEW YORK", "Revenue": 104116.88 },
  { "CITY": "MIAMI", "Revenue": 91911.39 }
]
*/
----------------------------------------------------------

/*
5. How many orders has each customer placed?
----------------------------------------------------------
Question: What is the number of orders per customer?

- Group the data by 'Customer Id'.
- Count the number of 'Order Number' for each customer.

Why? Identifies the most loyal and frequent customers.
*/

SELECT "Customer Id", COUNT("Order Number") AS Number_of_Orders
FROM shopify_sales
GROUP BY "Customer Id"
ORDER BY Number_of_Orders DESC;

/*
This shows the number of orders placed by each customer.


[
  { "Customer Id": "2865", "Number_of_Orders": 1 },
  { "Customer Id": "4987", "Number_of_Orders": 1 },
  { "Customer Id": "5037", "Number_of_Orders": 1 }
]
*/
----------------------------------------------------------

/*
6. What is the average quantity of items per order?
----------------------------------------------------------
Question: On average, how many items do customers purchase in a single order?

- Calculate the average of the 'Quantity' column.

Why? Helps with inventory planning and increasing average basket size.
*/

SELECT AVG("Quantity") AS Average_Quantity_Per_Order
FROM shopify_sales;

/*
This gives insight into customer purchasing behavior.


[
  { "Average_Quantity_Per_Order": 3.97 }
]
*/
----------------------------------------------------------

/*
7. What is the breakdown of sales by payment gateway?
----------------------------------------------------------
Question: How are sales distributed across different payment methods?

- Group the data by 'Gateway'.
- Count orders per gateway and calculate percentages.

Why? Shows which payment options customers prefer.
*/

SELECT "Gateway",
       COUNT("Order Number") * 100.0 / (SELECT COUNT(*) FROM shopify_sales) AS Payment_Percentage
FROM shopify_sales
GROUP BY "Gateway";

/*
This shows the share of sales processed by each payment gateway.


[
  { "Gateway": "shopify_payments", "Payment_Percentage": 50.75 },
  { "Gateway": "manual", "Payment_Percentage": 49.25 }
]
*/
----------------------------------------------------------

/*
8. What is the total amount of tax collected?
----------------------------------------------------------
Question: What is the sum of all taxes collected from sales?

- Sum the 'Total Tax' column.

Why? Crucial for financial reporting and compliance.
*/

SELECT SUM("Total Tax") AS Total_Tax_Collected
FROM shopify_sales;

/*
This is the total tax collected from all sales.


[
  { "Total_Tax_Collected": 249714.03 }
]
*/
----------------------------------------------------------

/*
9. What are the top 5 largest orders by total price?
----------------------------------------------------------
Question: Which orders had the highest total price?

- Order by 'Total Price Usd' in descending order.
- Pick the top 5 orders.

Why? Helps identify high-value transactions and bulk buyers.
*/

SELECT "Order Number", "Total Price Usd"
FROM shopify_sales
ORDER BY "Total Price Usd" DESC
LIMIT 5;

/*
This shows the most valuable individual transactions.


[
  { "Order Number": "2498", "Total Price Usd": 9976.24 },
  { "Order Number": "4921", "Total Price Usd": 9789.24 },
  { "Order Number": "6243", "Total Price Usd": 9734.54 },
  { "Order Number": "3398", "Total Price Usd": 9709.24 },
  { "Order Number": "3128", "Total Price Usd": 9692.74 }
]
*/
----------------------------------------------------------

/*
10. What is the customer distribution by state?
----------------------------------------------------------
Question: How are customers distributed geographically by state?

- Group by 'Billing Address Province'.
- Count unique customers per state.
- Order by customer count.

Why? Provides insights into customer base and helps regional strategy.
*/

SELECT "Billing Address Province", COUNT(DISTINCT "Customer Id") AS Number_of_Customers
FROM shopify_sales
GROUP BY "Billing Address Province"
ORDER BY Number_of_Customers DESC
LIMIT 3;

/*
This shows the number of unique customers in each state.


[
  { "Billing Address Province": "California", "Number_of_Customers": 234 },
  { "Billing Address Province": "Texas", "Number_of_Customers": 168 },
  { "Billing Address Province": "Florida", "Number_of_Customers": 150 }
]
*/